language: java
sudo: false

services:
  - redis-server

jdk:
  - oraclejdk7
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.5

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
  - secure: CEz4O1RmixHJno2A/oUL/zF8WKlgmmUKbu78xrnC80G0CsxOx7eJa3RSVV4NA5uoy4eVvMZS3CsWYXpfl2XTfdkQsgGEQDBbBNaQX/y0oBBusqT3bzVmWu2Lh90zFmh8iWylvhOadIUhe/D+jfKKZrCfXjTekRiNC/oYPzEB16w=
  - secure: hP05qbQEDObdiu3LivKfeK4tA9zV4i2Q4RcGhB4ufGE54nTSRfHeLuloVT1frP8jHeBB3w3w7CFTL6rtV94uCPy3iTpvqXrJJLlnP+8WF2EISzhAvA9oG0J4XxSXeFZ2+5xF7FbHFCCs7cwmJr5SOr15JT152T4geP5WJHlSysc=
  - secure: AWjkKlDz6vvzOHtz/ufK2ahEZNkMVpBosovi0K+J715mw6GjhYav4HfORc4PmuV55uiXZ8pxhFEAS1x4Aq4VnOndE9vti0azBtxopwvcx9ZmDSOzSx62ovTxV9PwtQ8KC0wHFE0B5N2ENhhly/A4mvoNPEv5EodF/l1JzfSfXEg=
  - secure: CR3d3i2qUuMqVxA1r8+mSsPXTEBp74bKShSLNwNm2mwYa0TSNNx0tnD5kkTJYKxQYmrRIwKqDFZdkD3hLrCXbp1bpI5XbkJL/fMEdCdbiuOo1xOr3q4oZEUSfige9RTOdUudII3JO1RcL8fPdEwjRQZut4Rqf6ueGqNbilMRSjU=
  - secure: Vxl1MpMeWktJNCRbhsMUn5M8gzlyaqt+bYAzpe9gics/NmCFNNviDY/YsxcLJ0gCv5ZD4sw/L7dLE490fmAGzlq5i1gViNJ2gnDmr5benizhcnyc+h2BtUn9+uYOKO4sRxcVTL7WOfxAQ+S2/SvmMYVP2MJ9cqVbjAhtEF4d8zI=
  - GRADLE_OPTS="-Dorg.gradle.daemon=false -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Xms2G -Xmx2G -Xss512k -XX:MaxPermSize=256m -verbose:gc"

before_install:
  - git config --global user.email "${GH_USER_EMAIL}"
  - git config --global user.name "${GH_USER}"

# Skip `./gradlew assemble`
install: /bin/true

before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"

script:
  - ./travis/publish.sh

