# Run `travis lint` when changing this file to avoid breaking the build.

# We need a full VM so that testcontainers can use Docker
# See https://docs.travis-ci.com/user/reference/overview/#for-a-particular-travisyml-configuration
arch: amd64           # arm64 is LXD containers which we can't use because we run Docker tests
os: linux             # required for arch different than amd64
dist: focal           # newest available distribution

language: java
# Intentionally don't use "jdk" key as it is coupled to jdk.java.net availability.
addons:
  apt:
    update: true

# Don't do a shallow clone to allow license plugin to correctly read git history.
git:
  depth: false

cache:
  directories:
  # zipkin-lens gets dependencies via NPM
  - $HOME/.npm
  - $HOME/.m2

services:
  - docker

before_install:
  - |
    # Use JDK 11, so we can release Java 6 bytecode
    OPENJDK_VERSION=11
    sudo apt-get -y install openjdk-${OPENJDK_VERSION}-jdk
    export JAVA_HOME=/usr/lib/jvm/java-${OPENJDK_VERSION}-openjdk-${TRAVIS_CPU_ARCH}/
    ./mvnw -version
  - |
    # Quiet Maven invoker logs (Downloading... when running zipkin-server/src/it)
    echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

    # Cache as help:evaluate is not quick
    export POM_VERSION=$(./mvnw help:evaluate -N -Dexpression=project.version -q -DforceStdout)

    # Disable testcontainers checks
    echo checks.disable=true > ~/.testcontainers.properties
  - |
    # Credentials entered into https://travis-ci.org/github/openzipkin/${REPO}/settings are access
    # controlled by branch (typically only master). Check to see if a well-known env is available
    # before attempting to log in.
    if [[ -n "$SONATYPE_USER" ]]; then
      # re-use this condition to control if we prepare Docker for multi-arch
      build-bin/setup_multiarch_docker

      # allocate commits to CI, not the owner of the deploy key
      git config user.name "zipkinci"
      git config user.email "zipkinci+zipkin-dev@googlegroups.com"

      # setup https authentication credentials, used by ./mvnw release:prepare
      git config credential.helper "store --file=.git/credentials"
      echo "https://$GH_TOKEN:@github.com" > .git/credentials

      # Log in to GitHub Container Registry and Docker Hub for releasing images
      echo "$GH_TOKEN"| docker login ghcr.io -u "$GH_USER" --password-stdin
      echo "$DOCKERHUB_PASSWORD"| docker login -u "$DOCKERHUB_USER" --password-stdin

      # ensure GPG commands work non-interactively
      export GPG_TTY=$(tty)
      # import signing key used for jar files
      echo ${GPG_SIGNING_KEY} | base64 --decode | gpg --batch --passphrase ${GPG_PASSPHRASE} --import
    fi

install: ./build-bin/go_offline
jobs:
  include:
    - name: default
      script: ./travis/publish.sh
      if: 'NOT tag =~ /^docker-/'
    - name: Re-push all Docker images
      script:
        - |
          set -euxo pipefail
          docker/bin/push_all $(echo "${TRAVIS_TAG}" | sed 's/^docker-//') &&
          # cleanup the release trigger, but don't fail if it was already there
          git push origin :"${TRAVIS_TAG}" || true
      if: 'type IN (push) and tag =~ /^docker-/'

branches:
  except:
    # Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
    # See https://github.com/travis-ci/travis-ci/issues/1532
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/9f1ee2f315d32956f8d6
    on_success: change
    on_failure: always


# Secure variables needed for release and publication
#
# When Travis, add to https://travis-ci.org/github/openzipkin/${REPO}/settings
#
# GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
#   - makes release commits and tags, also writes to GHCR if Docker
#   - needs repo:status, public_repo and if Docker write:packages, delete:packages
#   - referenced in .settings.xml
#   - store like this: echo "https://$GH_TOKEN:@github.com" > .git/credentials
# GH_USER=user_that_created_GH_TOKEN
# GPG_SIGNING_KEY=$(gpg -a --export-secret-keys zipkin-admin@googlegroups.com |base64)
#   - used to sign jars in release commands
#   - sent to keyserver.ubuntu.com
#   - import like this: echo ${GPG_SIGNING_KEY} | base64 --decode | gpg --batch --passphrase ${GPG_PASSPHRASE} --import
# GPG_PASSPHRASE=passphrase_for_GPG_SIGNING_KEY
#   - referenced in .settings.xml
# SONATYPE_USER=your_sonatype_account_token
#   - used to publish to Maven Central via https://oss.sonatype.org/#stagingRepositories
#   - needs access to io.zipkin via https://issues.sonatype.org/browse/OSSRH-16669
#   - generate via https://oss.sonatype.org/#profile;User%20Token
#   - referenced in .settings.xml
# SONATYPE_PASSWORD=password_to_SONATYPE_USER
#   - referenced in .settings.xml
# DOCKERHUB_USER=typically_dockerzipkindeployer
#   - only push top-level projects: zipkin zipkin-aws zipkin-dependencies zipkin-gcp to Docker Hub, only on release
#   - login like this: echo "$DOCKERHUB_PASSWORD"| docker login -u "$DOCKERHUB_USER" --password-stdin
# DOCKERHUB_PASSWORD=password_to_DOCKERHUB_USER
