#
# Copyright 2015-2019 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#
version: "3.6"
services:
  cassandra:
    build:
      context: ..
      dockerfile: docker/storage/cassandra/Dockerfile
    networks:
      default:
        aliases:
          - cassandra
        # Uncomment to expose the storage port for testing
    # ports:
    #   - 9042:9042
  zipkin:
    build:
      context: ..
      dockerfile: "${DOCKERFILE_PATH:-docker/Dockerfile}"
      args:
        source_branch: "${SOURCE_BRANCH:-master}"
    networks:
      default:
        aliases:
        - zipkin
    environment:
      - STORAGE_TYPE=cassandra3
      # When using the test docker image, or have schema pre-installed, you don't need to re-install it
      - CASSANDRA_ENSURE_SCHEMA=false
      # When overriding this value, note the minimum supported version is 3.9
      # If you you cannot run 3.9+, but can run 2.2+, set STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=cassandra
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    depends_on:
      - cassandra
  # Docker Hub automated test service - https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    image: appropriate/curl
    networks:
    - default
    command: -v --connect-timeout 5 --retry 30 --retry-connrefused --retry-delay 5 http://zipkin:9411/health
    depends_on:
    - zipkin
